apiVersion: v1
kind: Secret
metadata:
  name: employee-db-secret
  namespace: employee-management
  labels:
    app.kubernetes.io/name: employee-management
type: Opaque
stringData:
  DB_USER: employee_user
  DB_PASS: employee_pass
  AUTH_ADMIN_USER: admin
  AUTH_ADMIN_PASS: ChangeMe123!
  MYSQL_ROOT_PASSWORD: root_pass
